// Indian city → state/country mapping for auto-fill in client forms.
// Maps lowercase city name → { state, country }.
const CITY_MAP = {
  "vadodara": { state: "Gujarat", country: "India" },
  "baroda": { state: "Gujarat", country: "India" },
  "surat": { state: "Gujarat", country: "India" },
  "ahmedabad": { state: "Gujarat", country: "India" },
  "rajkot": { state: "Gujarat", country: "India" },
  "bhavnagar": { state: "Gujarat", country: "India" },
  "jamnagar": { state: "Gujarat", country: "India" },
  "gandhinagar": { state: "Gujarat", country: "India" },
  "anand": { state: "Gujarat", country: "India" },
  "bharuch": { state: "Gujarat", country: "India" },
  "valsad": { state: "Gujarat", country: "India" },
  "navsari": { state: "Gujarat", country: "India" },
  "mumbai": { state: "Maharashtra", country: "India" },
  "bombay": { state: "Maharashtra", country: "India" },
  "pune": { state: "Maharashtra", country: "India" },
  "nagpur": { state: "Maharashtra", country: "India" },
  "nashik": { state: "Maharashtra", country: "India" },
  "aurangabad": { state: "Maharashtra", country: "India" },
  "thane": { state: "Maharashtra", country: "India" },
  "nagpur": { state: "Maharashtra", country: "India" },
  "delhi": { state: "Delhi", country: "India" },
  "new delhi": { state: "Delhi", country: "India" },
  "noida": { state: "Uttar Pradesh", country: "India" },
  "gurgaon": { state: "Haryana", country: "India" },
  "gurugram": { state: "Haryana", country: "India" },
  "faridabad": { state: "Haryana", country: "India" },
  "lucknow": { state: "Uttar Pradesh", country: "India" },
  "kanpur": { state: "Uttar Pradesh", country: "India" },
  "agra": { state: "Uttar Pradesh", country: "India" },
  "varanasi": { state: "Uttar Pradesh", country: "India" },
  "meerut": { state: "Uttar Pradesh", country: "India" },
  "jaipur": { state: "Rajasthan", country: "India" },
  "jodhpur": { state: "Rajasthan", country: "India" },
  "udaipur": { state: "Rajasthan", country: "India" },
  "kota": { state: "Rajasthan", country: "India" },
  "ajmer": { state: "Rajasthan", country: "India" },
  "pushkar": { state: "Rajasthan", country: "India" },
  "bikaner": { state: "Rajasthan", country: "India" },
  "bangalore": { state: "Karnataka", country: "India" },
  "bengaluru": { state: "Karnataka", country: "India" },
  "mangalore": { state: "Karnataka", country: "India" },
  "mysore": { state: "Karnataka", country: "India" },
  "mysuru": { state: "Karnataka", country: "India" },
  "hubli": { state: "Karnataka", country: "India" },
  "hyderabad": { state: "Telangana", country: "India" },
  "warangal": { state: "Telangana", country: "India" },
  "chennai": { state: "Tamil Nadu", country: "India" },
  "madras": { state: "Tamil Nadu", country: "India" },
  "coimbatore": { state: "Tamil Nadu", country: "India" },
  "madurai": { state: "Tamil Nadu", country: "India" },
  "salem": { state: "Tamil Nadu", country: "India" },
  "trichy": { state: "Tamil Nadu", country: "India" },
  "tiruchirappalli": { state: "Tamil Nadu", country: "India" },
  "kolkata": { state: "West Bengal", country: "India" },
  "calcutta": { state: "West Bengal", country: "India" },
  "howrah": { state: "West Bengal", country: "India" },
  "durgapur": { state: "West Bengal", country: "India" },
  "bhubaneswar": { state: "Odisha", country: "India" },
  "cuttack": { state: "Odisha", country: "India" },
  "bhopal": { state: "Madhya Pradesh", country: "India" },
  "indore": { state: "Madhya Pradesh", country: "India" },
  "gwalior": { state: "Madhya Pradesh", country: "India" },
  "jabalpur": { state: "Madhya Pradesh", country: "India" },
  "patna": { state: "Bihar", country: "India" },
  "gaya": { state: "Bihar", country: "India" },
  "ranchi": { state: "Jharkhand", country: "India" },
  "jamshedpur": { state: "Jharkhand", country: "India" },
  "guwahati": { state: "Assam", country: "India" },
  "dispur": { state: "Assam", country: "India" },
  "chandigarh": { state: "Chandigarh", country: "India" },
  "amritsar": { state: "Punjab", country: "India" },
  "ludhiana": { state: "Punjab", country: "India" },
  "jalandhar": { state: "Punjab", country: "India" },
  "shimla": { state: "Himachal Pradesh", country: "India" },
  "dehradun": { state: "Uttarakhand", country: "India" },
  "haridwar": { state: "Uttarakhand", country: "India" },
  "panaji": { state: "Goa", country: "India" },
  "goa": { state: "Goa", country: "India" },
  "kochi": { state: "Kerala", country: "India" },
  "cochin": { state: "Kerala", country: "India" },
  "trivandrum": { state: "Kerala", country: "India" },
  "thiruvananthapuram": { state: "Kerala", country: "India" },
  "kozhikode": { state: "Kerala", country: "India" },
  "calicut": { state: "Kerala", country: "India" },
  "raipur": { state: "Chhattisgarh", country: "India" },
  "bhubaneswar": { state: "Odisha", country: "India" },
  "vijayawada": { state: "Andhra Pradesh", country: "India" },
  "visakhapatnam": { state: "Andhra Pradesh", country: "India" },
  "tirupati": { state: "Andhra Pradesh", country: "India" },
  "amravati": { state: "Andhra Pradesh", country: "India" }
};

export function lookupCity(cityName) {
  if (!cityName) return null;
  const key = cityName.trim().toLowerCase();
  return CITY_MAP[key] || null;
}