import { Camera, PartyPopper, Briefcase, Building2, Sparkles, Megaphone, Ruler } from "lucide-react";

// Sample data behind the hero's category chips. Picking a chip swaps the phone preview and the
// floating cards around it — the work-item word (Events / Projects / Campaigns…), the numbers,
// the revenue bars and the example names — so each business type sees its own version of the app.
export const HERO_PROFILES = [
  {
    id: "photography", label: "Photography", icon: Camera, plural: "Events",
    revenue: "₹18.4L", growth: "24%", count: "7",
    upcoming: ["Wedding — Rahul & Priya", "Corporate — TechCorp"],
    chart: [35, 50, 40, 65, 55, 80, 95],
    event: { title: "Wedding — Rahul & Priya", meta: "Sat, 14 Feb · 3 on team" },
    payment: "₹45,000", quoteBy: "TechCorp",
    lead: { name: "Anita S.", what: "Pre-wedding shoot" },
    week: "7 events this week",
  },
  {
    id: "events", label: "Event Management", icon: PartyPopper, plural: "Events",
    revenue: "₹42.6L", growth: "31%", count: "12",
    upcoming: ["Sangeet Night — Kapoor Family", "Product Launch — Nova Motors"],
    chart: [30, 45, 60, 50, 72, 68, 92],
    event: { title: "Sangeet Night — Kapoor Family", meta: "Sat, 21 Feb · 12 on crew" },
    payment: "₹1,25,000", quoteBy: "Nova Motors",
    lead: { name: "Rohan K.", what: "Corporate gala" },
    week: "12 events this week",
  },
  {
    id: "freelancers", label: "Freelancers", icon: Briefcase, plural: "Projects",
    revenue: "₹6.2L", growth: "18%", count: "5",
    upcoming: ["Logo Design — Cafe Brew", "Website Revamp — Kiran & Co"],
    chart: [25, 40, 35, 55, 50, 70, 85],
    event: { title: "Logo Design — Cafe Brew", meta: "Due Fri, 20 Feb · Solo" },
    payment: "₹18,000", quoteBy: "Kiran & Co",
    lead: { name: "Neha P.", what: "Brand identity" },
    week: "5 projects this week",
  },
  {
    id: "studios", label: "Studios", icon: Building2, plural: "Projects",
    revenue: "₹24.8L", growth: "22%", count: "9",
    upcoming: ["Brand Shoot — Aura Skincare", "Podcast Setup — Echo FM"],
    chart: [40, 48, 52, 45, 70, 75, 90],
    event: { title: "Brand Shoot — Aura Skincare", meta: "Tue, 17 Feb · 6 on team" },
    payment: "₹85,000", quoteBy: "Echo FM",
    lead: { name: "Dev M.", what: "Product catalogue" },
    week: "9 projects this week",
  },
  {
    id: "creators", label: "Creators", icon: Sparkles, plural: "Collabs",
    revenue: "₹3.4L", growth: "41%", count: "8",
    upcoming: ["Reel Series — GlowUp", "Sponsored Video — FitFuel"],
    chart: [20, 35, 30, 60, 55, 78, 98],
    event: { title: "Reel Series — GlowUp", meta: "Thu, 19 Feb · 2 deliverables" },
    payment: "₹30,000", quoteBy: "FitFuel",
    lead: { name: "Isha R.", what: "Brand collab" },
    week: "8 collabs this week",
  },
  {
    id: "agencies", label: "Agencies", icon: Megaphone, plural: "Campaigns",
    revenue: "₹58.0L", growth: "19%", count: "14",
    upcoming: ["Festive Campaign — Zenith Retail", "Social Retainer — PixelPay"],
    chart: [45, 50, 48, 62, 70, 74, 88],
    event: { title: "Festive Campaign — Zenith Retail", meta: "Mon, 23 Feb · 8 on team" },
    payment: "₹2,40,000", quoteBy: "PixelPay",
    lead: { name: "Karan T.", what: "Launch campaign" },
    week: "14 campaigns this week",
  },
  {
    id: "architects", label: "Architects / Interior", icon: Ruler, plural: "Projects",
    revenue: "₹36.5L", growth: "26%", count: "6",
    upcoming: ["Villa Interiors — Desai Residence", "Office Fit-out — Orbit Labs"],
    chart: [28, 38, 50, 46, 66, 72, 90],
    event: { title: "Villa Interiors — Desai Residence", meta: "Wed, 18 Feb · Site visit" },
    payment: "₹1,50,000", quoteBy: "Orbit Labs",
    lead: { name: "Pooja V.", what: "3BHK interiors" },
    week: "6 projects this week",
  },
];
